BurgerManiaApp/BurgerManiaApp/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BurgerManiaApp.Areas.Admin.Controllers
{
    public class HomeController : AdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Areas/Admin/Controllers/UserController.cs
using BurgerManiaApp.Core.Contracts.Admin;
using BurgerManiaApp.Extensions;
using Microsoft.AspNetCore.Mvc;

namespace BurgerManiaApp.Areas.Admin.Controllers
{
    public class UserController : AdminController
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> All()
        {
            var model = await userService.All();

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            return View(model);
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Areas/Deliverer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace BurgerManiaApp.Areas.Deliverer.Controllers
{
    public class HomeController : DelivererController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Controllers/HomeController.cs
using static BurgerManiaApp.Areas.Admin.Constants.AdminConstants;
using static BurgerManiaApp.Areas.Deliverer.Constants.DelivererConstants;
using BurgerManiaApp.Core.Contracts;
using BurgerManiaApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BurgerManiaApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductService productService;

        public HomeController(ILogger<HomeController> logger, IProductService productService)
        {
            _logger = logger;
            this.productService = productService;
        }

        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole(AdminRoleName))
            {
                return RedirectToAction("Index", "Home", new { area = "Admin" });
            }
            if (this.User.IsInRole(DelivererRoleName))
            {
                return RedirectToAction("Index", "Home", new { area = "Deliverer" });
            }

            var model = await productService.LastThreeBurgers();

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Controllers/OrderController.cs
using System.Diagnostics;
using BurgerManiaApp.Core.Contracts;
using BurgerManiaApp.Core.Models.Order;
using BurgerManiaApp.Extensions;
using BurgerManiaApp.Models;
using Microsoft.AspNetCore.Mvc;



namespace BurgerManiaApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService orderService;
        private readonly ICartService cartService;

        public OrderController(IOrderService orderService,
            ICartService cartService)
        {
            this.orderService = orderService;
            this.cartService = cartService;
        }

        public async Task<IActionResult> All(OrdersViewModel model)
        {
            var userId = HttpContext.GetUserId();
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            model = await orderService.GetAllOrders(userId);

            return View(model);
        }

        public async Task<IActionResult> MoreAbout(int id)
        {
            var userId = HttpContext.GetUserId();

            var order = await orderService.GetCurrentOrderInfo(id, userId);

            return View(order);
        }

        public async Task<IActionResult> CreateOrder()
        {
            var userId = HttpContext.GetUserId();
            CheckoutViewModel model = new CheckoutViewModel
            {
                UserCart = await cartService.GetOrCreateCart(userId)
            };

            if (model.UserCart.CartItems.Count() < 1)
            {
                return RedirectToAction("Index", "Cart");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(CheckoutViewModel model)
        {
            var userId = HttpContext.GetUserId();
            var cart = await cartService.GetOrCreateCart(userId);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (ModelState.IsValid)
            {
                await orderService.CreateOrder(userId,
                                             cart.Id,
                                             model.EmailAddress,
                                             model.FirstName,
                                             model.LastName,
                                             model.PhoneNumber,
                                             model.PostalCode,
                                             model.StreetAddress,
                                             model.City,
                                             model.AddressName);

                return RedirectToAction("All", "Product");
            }

            model.UserCart = await cartService.GetOrCreateCart(userId);

            return View("CreateOrder", model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <main role="main" class="pb-3">
        <div class="mt-4 p-5 text-center" style="background-color: #eee;">
            <h2 class="display-4">Hello, Admin!</h2>
            <p class="lead mb-1 mt-3">
                This is your administrator area - you can <b>read</b>, <b>create</b>,
                <b>delete</b> and <b>edit</b> products.            
            </p>
            <p class="lead mt-1">
                You can also see <b>all users</b> in the system.
            </p>
            <hr class="my-4">
            <a asp-area="" asp-controller="Product" asp-action="All"
               class="btn btn-primary btn-lg">All Products</a>
            <a asp-area="" asp-controller="Product" asp-action="Add"
               class="btn btn-primary btn-lg">Add Product</a>
            <span>  |   </span>
            <a asp-area="" asp-controller="Order" asp-action="All"
               class="btn btn-primary btn-lg">My Orders</a>
            <span>  |   </span>
            <a asp-area="Admin" asp-controller="User" asp-action="All"
               class="btn btn-primary btn-lg">All Users</a>
           @if (this.User.IsInRole(DelivererRoleName))
            {
                <span>  |   </span>
                <a asp-area="Deliverer" asp-controller="Order" asp-action="All"
               class="btn btn-primary btn-lg">Orders</a>
                <span>  |   </span>
            }
        </div>
    </main>
</div>