BurgerManiaApp/BurgerManiaApp/Areas/Admin/Controllers/RoleController.cs
using BurgerManiaApp.Core.Contracts.Admin;
using BurgerManiaApp.Core.Models.Admin;
using BurgerManiaApp.Infractructure.Data.Entities.Account;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BurgerManiaApp.Areas.Admin.Controllers
{
    public class RoleController : AdminController
    {
        private readonly IRoleService roleService;

        public RoleController(IRoleService roleService)
        {
            this.roleService = roleService;
        }

        public async Task<IActionResult> AddRole(string id)
        {
            var result =await roleService.GetModel(id);
            var model = new RoleModel()
            {
                Email = result.Email,
                Name = result.Name,
                Roles = result.Roles.ToList(),
            };

            return View(model);
        }

        public async Task<IActionResult> AddRoleToUser(string id,string role)
        {
            await roleService.AddRole(id,role);

            return RedirectToAction("Index", "Home");
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Controllers/ProductController.cs
using static BurgerManiaApp.Areas.Admin.Constants.AdminConstants;
using BurgerManiaApp.Core.Contracts;
using BurgerManiaApp.Core.Models.Products;
using BurgerManiaApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BurgerManiaApp.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }


        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery] AllProductsQueryModel query)
        {
            var result = await productService.All(
               query.Category,
               query.SearchTerm,
               query.Sorting,
               query.CurrentPage,
               AllProductsQueryModel.ProductPerPage);

            query.TotalProductsCount = result.TotalProductsCount;
            query.Categories = await productService.AllCategoriesNames();
            query.Products = result.Products;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            if (!(this.User.IsInRole(AdminRoleName)))
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            var model = new ProductModel()
            {
                ProductCategories = await productService.AllCategories()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ProductModel model)
        {
            if (!(this.User.IsInRole(AdminRoleName)))
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            if ((await productService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exists");
            }

            if (!ModelState.IsValid)
            {
                model.ProductCategories = await productService.AllCategories();

                return View(model);
            }

            int id = await productService.Create(model);

            return RedirectToAction(nameof(Details), new { id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            if ((await productService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (!(this.User.IsInRole(AdminRoleName)))
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            var product = await productService.ProductDetailsById(id);
            var categoryId = await productService.GetProductCategoryId(id);

            var model = new ProductModel()
            {
                CategoryId = categoryId,
                Description = product.Description,
                ImageUrl = product.ImageUrl,
                Price = product.Price,
                Name = product.Name,
                ProductCategories = await productService.AllCategories(),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProductModel model)
        {
            if ((await productService.Exists(model.Id)) == false)
            {
                ModelState.AddModelError("", "Product does not exist");

                model.ProductCategories = await productService.AllCategories();

                return View(model);
            }

            if (!(this.User.IsInRole(AdminRoleName)))
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            if ((await productService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist");

                model.ProductCategories = await productService.AllCategories();

                return View(model);
            }
            if (ModelState.IsValid == false)
            {
                model.ProductCategories = await productService.AllCategories();

                return View(model);
            }

            await productService.Edit(model.Id, model);
            return RedirectToAction(nameof(Details), new { model.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await productService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (!(this.User.IsInRole(AdminRoleName)))
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            var product = await productService.ProductDetailsById(id);
            var model = new ProductDetailsModel()
            {
                Description = product.Description,
                ImageUrl = product.ImageUrl,
                Name = product.Name
            };

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id, ProductDetailsModel model)
        {
            if ((await productService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (!(this.User.IsInRole(AdminRoleName)))
            {
                return RedirectToAction("AccessDenied", "Error");
            }

            await productService.Delete(id);

            return RedirectToAction(nameof(All));
        }


        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            if ((await productService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var model = await productService.ProductDetailsById(id);

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BurgerManiaApp/BurgerManiaApp/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BurgerManiaApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Burger Mania</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="All">Menu</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @RenderBody()
   @* <footer class="border-top footer text-muted bg-dark">
        <div class="text-center">
            <div class="copyright text-center mb-0 ">
                &copy; Copyright <strong><span>Martin Grahovski</span></strong>. All Rights
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BurgerManiaApp/BurgerManiaApp/Areas/Admin/Views/Shared/_UserPartial.cshtml
@model UserServiceModel


<div class="card w-100 mb-1">
    <div class="card-body">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h5 class="card-title">User-Email: @Model.Email</h5>
                    <p class="mb-0">User-Full Name: @(Model.FullName == null ? "None" : Model.FullName)</p>
                    <p>User-Phone Number: @(Model.PhoneNumber == null ? "None" : Model.PhoneNumber)</p>
                </div>
                <div class="col">
                    <h5 class="card-title">Roles:</h5>
                    @foreach (var item in Model.Roles)
                    {
                        <p class="mb-0">@(item)</p>
                    }
                </div>
            </div>
        </div>
        <a asp-area="Admin" asp-controller="Role" asp-action="AddRole" asp-route-id="@Model.Id" class="btn btn-success">Add Role</a>
    </div>
</div>